language: python
python:
    - "3.4"
# Command to install dependencies
install:
    - pip install .

script:
    - lsb_release -a

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libzmq3-dev